steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia-northeast3-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE}', '.' ]
images:
- 'asia-northeast3-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE}'

timeout: 3600s